### PR TITLE
I Made some textures

### PR DESCRIPTION
**Pull request by Falkory220**
Didnt know how to work with the base testosterone pallet so kinda made up my own pallet for it, the mob effect icon was made when it was 4am so it might be bad i dont know. if you have feedback or i forgot anything let me know and ill work on it when i can.

This was fun to texture

### CODE REVIEW

**Comment by MayaqqDev** [comment]
Sorry for getting to you so late, all of these look amazing!
I will try to include those with an update later down the line if thats fine! (once I figure out programmer art stuff)

**Comment by Falkory220** [comment]
yeah thats fine, might tweak a few things in the meantime, also might have a go at re-texturing the centrifuge?

**Comment by MayaqqDev** [comment]
I am pretty happy with the centrifuge textures

**Comment by Falkory220** [comment]
yeah the centrifuge looks fine all id probably really do is bulk out the copper corners a bit to make it a bit more inline with creates tanks, but it looks fine as is

**Pull request merged**
