### PR TITLE
Add Russian translation (ru_ru.json)

### PR DESCRIPTION
**Pull request by TheAnaxMan**
Russian translation added, original meanings taken from en_en.json

### CODE REVIEW

**Comment by MayaqqDev** [comment]
Hello, sorry for getting to this only a bit later. Could you use the datagen class instead?

**Comment by MayaqqDev** [comment]
Could you please make a new pull request to the new branch with all the new translations?

**Comment by TheAnaxMan** [comment]
> Could you please make a new pull request to the new branch with all the new translations?

Yes, I will create it within a week

**Comment by TheAnaxMan** [comment]
> Could you please make a new pull request to the new branch with all the new translations?

**Comment by MayaqqDev** [comment]
Awesome!

**Pull request closed without merging**
