### PR TITLE
Language Fixes

### PR DESCRIPTION
**Pull request by RepeatGitHub**
Just a few little things to add capitalization consistency and keeping it similar to original Create's pondering lines.

(Also could someone backport the en_us files to older versions too? This is just a small fork and I didn't want to manually copy all the changes to all the branches myself.)

### CODE REVIEW

**Comment by MayaqqDev** [comment]
I am sorry but I cant accept this pr, could you please change the datagen file instead?

**Comment by RepeatGitHub** [comment]
Oh, what branch is it in?

**Comment by MayaqqDev** [comment]
Its in the folder that autogenerates it

**Comment by MayaqqDev** [comment]
meh, I will merge this and add it myself

**Comment by MayaqqDev** [comment]
thanks

**Comment by RepeatGitHub** [comment]
sry abt not updating the fork, i couldn't find the folder 😥

**Pull request merged**
